name: Rust

on:
  push:
    branches: ["slaveholder"]
  pull_request:
    branches: ["slaveholder"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          override: true
      - name: Build
        run: cargo build --verbose --features full
      - name: Run tests
        run: cargo test --verbose --features full
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
